#
- name: php - add repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: "present"
    update_cache: yes

# xdebug installation described in xdebug.yml
- name: php - install base packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "php7.2-common"
    - "php7.2-cli"
    - "php7.2-fpm"
    - "php7.2-pgsql"
    - "php7.2-mysql"
    - "php7.2-gd"
    - "php7.2-bz2"
    - "php7.2-zip"
    - "php7.2-json"
    - "php7.2-xml"
    - "php7.2-curl"
    - "php7.2-intl"
    - "php7.2-mbstring"
    - "php7.2-bcmath"
    - "php7.2-soap"

- name: php - ensure pid directory exists
  file:
    path: "/run/php"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755
